server:
  port: 8080

spring:
  application:
    name: Dash

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

  instance:
    hostname: localhost



logging:
  level:
    com:
      netflix:
        discovery=DEBUG: