server:
  port: 8081

spring:

  application:
    name: Resource-Server

  servlet:
    multipart:
      max-file-size: 5MB

  #security:
    #oauth2:
      #resource-server:
        #jwt:
          #issuer-uri: http://auth-server:9000


application:
  bucket:
    dash-analytics-test


cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: us-east-2
    stack:
      auto: false


openai:
  model:
    version: gpt-3.5-turbo
  credentials:
    secret-key: ${GPT_API_KEY}


eureka:
  client:
    service-url:
      defaultZone: http://172.31.33.187:8761/eureka
    fetch-registry: true
    register-with-eureka: true

  instance:
    hostname: 172.31.33.187
