server:
  port: 8081

spring:

  application:
    name: Resource-Server

  servlet:
    multipart:
      max-file-size: 5MB

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://auth-server:80


application:
  bucket:
    dash-analytics-test


cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
      static: us-east-2
    stack:
      auto: false


openai:
  model:
    version: gpt-3.5-turbo
  credentials:
    secret-key:


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

  instance:
    hostname: localhost
