server:
  port: 9000

spring:
  application:
    name: OAuthorization-Service
  data:
    mongodb:
      uri: mongodb+srv://gpmoral:gMC20002@dev-cluster.ul8671y.mongodb.net/?retryWrites=true&w=majority
      database: Dash-Analytics